Performance Increase, Update code to work
fuseio/fuse-nft-subgraph pull request #8
Opened 2022-05-09 06:44 UTC by GundamDweeb

The old subgraph cannot be compiled due to many factors - namely it being out of date with the current versions of graph-cli and graph-ts.

It cannot be built, or deployed, so it needed updating. The currently deployed subgraph is only working because it hasn't been touched in a while.

There is a large performance increase by indexing each contract via templating.

I have reworked the structure of the schema for better indexing as well, and better lookup times on queries.

2022-05-12 08:50 UTC, GundamDweeb commented
@mul53 @leonprou 

Please see - https://thegraph.com/hosted-service/subgraph/gundamdweeb/fuse-network-erc721?query=Revealed%20Cozy

2022-05-18 00:11 UTC, mul53 requested changes

2022-05-18 00:11 UTC, mul53 commented on package.json
> +    "deploy": "graph deploy gundamdweeb/fuse-network-erc721  --ipfs https://api.thegraph.com/ipfs/ --node https://api.thegraph.com/deploy/",
revert back the changes

2022-05-18 00:11 UTC, mul53 commented on src/utils.ts
> +  if(tokenURI != null || tokenURI != ""){
can you format the code here, so it's consistent with the rest of the codebase

2022-05-18 10:14 UTC, GundamDweeb commented
@mul53 Requested changes have been resolved! :)

2022-10-11 09:25 UTC, merged